"""empty message

Revision ID: 20a98183ec3f
Revises: 
Create Date: 2018-05-30 05:12:17.868208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a98183ec3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('expiration_ttm', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_dttm', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('create_dttm', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login')
    # ### end Alembic commands ###
